### PR TITLE
Split based on AST context

### LINKED ISSUE #3: Rule does not ignore certain cases of URLs/paths
The example I came across was in a markdown doc, where textlint-rule-one-sentence-per-line was finding issue in the following snippet:

> The Backoffice application will be available at:  
> `https://{Application Load Balancer DNS NAME}/login?continue=/backoffice`

It wanted to split on the `?` character in the example URL. Further testing of normal prose in code spans also showed it was not skipped.

I would expect a rule to ignore things that are addresses or paths, and to ignore things in `code spans`. This could either be added as a default, or a settings option could be supported in .textlintrc either to toggle this behaviour or in a general case to permit pattern matched skipping.

### PR DESCRIPTION
**Pull request by kimburgess**
Resolves #3 and #7.

Perform splits based on AST context, rather than raw paragraph string.

Note the current state of this PR does cause a regression for link titles and emphasis blocks. These are _not_ detected.

### CODE REVIEW

**Comment by Benjamin-Lee** [comment]
I am fine with these regressions for now. Link titles on multiple lines are quite uncommon and long em blocks are a worthwhile sacrifice for closing #3 and #7. Thanks for the contribution!

**Comment by kimburgess** [comment]
Oh excellent. I had forgotten this PR has dangling and still tracking this branch. Those fresh commits are hopefully useful too though!

**Comment by Benjamin-Lee** [comment]
I invited you as a maintainer on the project since your knowledge of text lint is clearly much better than mine. Welcome!

**Comment by kimburgess** [comment]
Thank you, although I will have to decline as I have quite a few other projects that need tending to.

I am happy to continue as a contributor and will submit anything commonly useful back this way to prevent fragmentation.

**Pull request merged**
